#### JHU Data Cleansing Week 3 Quiz

## Quiz1

```{r}
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv",destfile = "quiz2data.csv")
data <- read.csv("quiz2data.csv")
logic <- data$ACR ==3 & data$AGS == 6
which(logic)
```

## Quiz2

```{r}
library(jpeg)

download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fjeff.jpg", destfile = "quiz2jpeg.jpg")
jpgdat = readJPEG("quiz2jpeg.jpg", native = TRUE)
quantile(jpgdat, probs = c(0.3, 0.8))
```

## Quiz 3

```{r}
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv", destfile = "quiz3data.csv")
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv", destfile = "quiz3data2.csv")

countries = fread("quiz3data.csv", skip=4, nrows = 190, select = c(1, 2, 4, 5), col.names=c("CountryCode", "Rank", "Economy", "Total"))
education = fread("quiz3data2.csv")
all = merge(countries, education, by = "CountryCode")
dim(all)
```

```{r}
all <- arrange(all, desc(Rank))

head(all,13)[33]
```


## Quiz 4
```{r}
unique(all$`Income Group`)
```
```{r}
tapply(all$Rank, all$`Income Group`, mean)
```

## Quiz 5

```{r}
library(Hmisc)
all$RankGroups <- cut2(all$Rank, g=5)
table(all$RankGroups, all$`Income Group`)

table(all$RankGroups, all$`Income Group`)[4]
```

